### ISSUE TITLE
Classes rework suggestion

### ISSUE THREAD

**Issue by Gabo6480** [qSided/Classes1.16#1]
I feel like the classes could be more than an early boost to your levels.
Something that could be interesting is having branching classes, at the beginning you would only have some basic classes:

- Fighter:
      Lightly focuses on Endurance, Combat, Slayer and Archery

- Gatherer:
      Lightly focuses on Cooking, Farming, Hunter and Fishing

- Worker:
      Lightly focuses on Woodcutting, Mining and Excavation

- Craftsman:
      Lightly focuses on Building, Smithing and Crafting

- Explorer:
      Lightly focuses on Agility, Taming, Swimming and Flying

- Mage:
      Lightly focuses on Magic and Alchemy
     

These classes will give extra passive experience for the skills it focuses on instead of giving you free levels.
Then these basic classes will allow further specialization in the form of sub-classes, for example:

 
- Fighter specializes into:
        - Tank: Focuses on Endurance and lightly into Combat
        - Warrior: Focuses on Combat and lightly into Slayer
        - Archer: Focuses on Archery and lightly into Agility

- Gatherer specializes into:
        - Huntsman: Focuses on Hunter and lightly into Fishing
        - Cook: Focuses on Cooking and lightly into Farming

 

I think you get the idea, in order to pick one of these sub-classes you would need to have certain level in the skills it focuses and you would get even more extra experience.
After this you could even have sub-sub-classes for even further specialization, and if you want you could even add special effects such as permanent potion effects, passive enchantments, extra loot, passive abilities with cooldowns, etc.

**Comment by Gabo6480** [comment]
Woops, it picked all the labels automatically, sorry

**Comment by qSided** [comment]
That's fine, thank you for moving it here :)

**Comment by qSided** [comment]
Looking back it this, a lot of these were actually already planned. But I decided to implement the class rework you suggested.
I'll be making a few changes to the ideas you gave in order to fit more to what I envisioned for Classes.
